<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
* @var yii\web\View $this
* @var common\models\Reservation $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="reservation-form">

    <?php $form = ActiveForm::begin([
    'id' => 'Reservation',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-error'
    ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>
            

<!-- attribute idUser -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'idUser')->dropDownList(
    \yii\helpers\ArrayHelper::map(common\models\User::find()->all(), 'id', 'id'),
    [
        'prompt' => 'Select',
        'disabled' => (isset($relAttributes) && isset($relAttributes['idUser'])),
    ]
); ?>

<!-- attribute idTable -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'idTable')->dropDownList(
    \yii\helpers\ArrayHelper::map(common\models\Table::find()->all(), 'idTable', 'idTable'),
    [
        'prompt' => 'Select',
        'disabled' => (isset($relAttributes) && isset($relAttributes['idTable'])),
    ]
); ?>

<!-- attribute idDate -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'idDate')->dropDownList(
    \yii\helpers\ArrayHelper::map(common\models\Date::find()->all(), 'idDate', 'idDate'),
    [
        'prompt' => 'Select',
        'disabled' => (isset($relAttributes) && isset($relAttributes['idDate'])),
    ]
); ?>

<!-- attribute status -->
			<?= $form->field($model, 'status')->textInput() ?>

<!-- attribute advance -->
			<?= $form->field($model, 'advance')->textInput() ?>

<!-- attribute qtyPersons -->
			<?= $form->field($model, 'qtyPersons')->textInput() ?>

<!-- attribute reservationDate -->
			<?= $form->field($model, 'reservationDate')->textInput() ?>

<!-- attribute clientName -->
			<?= $form->field($model, 'clientName')->textInput(['maxlength' => true]) ?>

<!-- attribute clientPhone -->
			<?= $form->field($model, 'clientPhone')->textInput(['maxlength' => true]) ?>
        </p>
        <?php $this->endBlock(); ?>
        
        <?=
    Tabs::widget(
                 [
                    'encodeLabels' => false,
                    'items' => [ 
                        [
    'label'   => Yii::t('app', 'Reservation'),
    'content' => $this->blocks['main'],
    'active'  => true,
],
                    ]
                 ]
    );
    ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
        '<span class="glyphicon glyphicon-check"></span> ' .
        ($model->isNewRecord ? 'Create' : 'Save'),
        [
        'id' => 'save-' . $model->formName(),
        'class' => 'btn btn-success'
        ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

