<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
* @var yii\web\View $this
* @var common\models\Reservation $model
*/
$copyParams = $model->attributes;

$this->title = Yii::t('app', 'Reservation');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Reservations'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->idReservation, 'url' => ['view', 'idReservation' => $model->idReservation]];
$this->params['breadcrumbs'][] = 'View';
?>
<div class="giiant-crud reservation-view">

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <h1>
        <?= Yii::t('app', 'Reservation') ?>
        <small>
            <?= $model->idReservation ?>
        </small>
    </h1>


    <div class="clearfix crud-navigation">

        <!-- menu buttons -->
        <div class='pull-left'>
            <?= Html::a(
            '<span class="glyphicon glyphicon-pencil"></span> ' . 'Edit',
            [ 'update', 'idReservation' => $model->idReservation],
            ['class' => 'btn btn-info']) ?>

            <?= Html::a(
            '<span class="glyphicon glyphicon-copy"></span> ' . 'Copy',
            ['create', 'idReservation' => $model->idReservation, 'Reservation'=>$copyParams],
            ['class' => 'btn btn-success']) ?>

            <?= Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . 'New',
            ['create'],
            ['class' => 'btn btn-success']) ?>
        </div>

        <div class="pull-right">
            <?= Html::a('<span class="glyphicon glyphicon-list"></span> '
            . 'Full list', ['index'], ['class'=>'btn btn-default']) ?>
        </div>

    </div>

    <hr />

    <?php $this->beginBlock('common\models\Reservation'); ?>

    
    <?= DetailView::widget([
    'model' => $model,
    'attributes' => [
    // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'idUser',
    'value' => ($model->getIdUser0()->one() ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['user/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->getIdUser0()->one()->id, ['user/view', 'id' => $model->getIdUser0()->one()->id,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Reservation'=>['idUser' => $model->idUser]])
        : 
        '<span class="label label-warning">?</span>'),
],
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'idTable',
    'value' => ($model->getIdTable0()->one() ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['table/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->getIdTable0()->one()->idTable, ['table/view', 'idTable' => $model->getIdTable0()->one()->idTable,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Reservation'=>['idTable' => $model->idTable]])
        : 
        '<span class="label label-warning">?</span>'),
],
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'idDate',
    'value' => ($model->getIdDate0()->one() ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['date/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->getIdDate0()->one()->idDate, ['date/view', 'idDate' => $model->getIdDate0()->one()->idDate,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Reservation'=>['idDate' => $model->idDate]])
        : 
        '<span class="label label-warning">?</span>'),
],
        'status',
        'advance',
        'qtyPersons',
        'reservationDate',
        'clientName',
        'clientPhone',
    ],
    ]); ?>

    
    <hr/>

    <?= Html::a('<span class="glyphicon glyphicon-trash"></span> ' . 'Delete', ['delete', 'idReservation' => $model->idReservation],
    [
    'class' => 'btn btn-danger',
    'data-confirm' => '' . 'Are you sure to delete this item?' . '',
    'data-method' => 'post',
    ]); ?>
    <?php $this->endBlock(); ?>


    
    <?= Tabs::widget(
                 [
                     'id' => 'relation-tabs',
                     'encodeLabels' => false,
                     'items' => [
 [
    'label'   => '<b class=""># '.$model->idReservation.'</b>',
    'content' => $this->blocks['common\models\Reservation'],
    'active'  => true,
],
 ]
                 ]
    );
    ?>
</div>
