<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "reservation".
 *
 * @property integer $idReservation
 * @property integer $idUser
 * @property integer $idTable
 * @property integer $idDate
 * @property integer $status
 * @property string $clientName
 * @property string $clientPhone
 * @property integer $advance
 * @property integer $qtyPersons
 * @property integer $reservationDate
 *
 * @property \common\models\User $idUser0
 * @property \common\models\Table $idTable0
 * @property \common\models\Date $idDate0
 * @property string $aliasModel
 */
abstract class Reservation extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'reservation';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['idUser', 'idTable', 'idDate', 'status', 'advance', 'qtyPersons', 'reservationDate'], 'integer'],
            [['idTable', 'idDate', 'status', 'clientName', 'clientPhone', 'qtyPersons', 'reservationDate'], 'required'],
            [['clientName', 'clientPhone'], 'string', 'max' => 255],
            [['idUser'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\User::className(), 'targetAttribute' => ['idUser' => 'id']],
            [['idTable'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Table::className(), 'targetAttribute' => ['idTable' => 'idTable']],
            [['idDate'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Date::className(), 'targetAttribute' => ['idDate' => 'idDate']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'idReservation' => 'Id Reservation',
            'idUser' => 'Id User',
            'idTable' => 'Id Table',
            'idDate' => 'Id Date',
            'status' => 'Status',
            'clientName' => 'Client Name',
            'clientPhone' => 'Client Phone',
            'advance' => 'Advance',
            'qtyPersons' => 'Qty Persons',
            'reservationDate' => 'Reservation Date',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdUser0()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'idUser']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdTable0()
    {
        return $this->hasOne(\common\models\Table::className(), ['idTable' => 'idTable']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdDate0()
    {
        return $this->hasOne(\common\models\Date::className(), ['idDate' => 'idDate']);
    }




}
