<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "table".
 *
 * @property integer $idTable
 * @property integer $idVip
 * @property string $code
 *
 * @property \common\models\Reservation[] $reservations
 * @property \common\models\Vip $idVip0
 * @property string $aliasModel
 */
abstract class Table extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'table';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['idVip', 'code'], 'required'],
            [['idVip'], 'integer'],
            [['code'], 'string', 'max' => 255],
            [['idVip'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Vip::className(), 'targetAttribute' => ['idVip' => 'idVip']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'idTable' => 'Id Table',
            'idVip' => 'Id Vip',
            'code' => 'Code',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getReservations()
    {
        return $this->hasMany(\common\models\Reservation::className(), ['idTable' => 'idTable']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdVip0()
    {
        return $this->hasOne(\common\models\Vip::className(), ['idVip' => 'idVip']);
    }




}
