<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "user_data".
 *
 * @property integer $idListName
 * @property integer $idUser
 * @property string $listName
 * @property string $fullName
 * @property string $instagram
 * @property string $phone
 *
 * @property \common\models\User $idUser0
 * @property string $aliasModel
 */
abstract class UserData extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user_data';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['idUser'], 'required'],
            [['idUser'], 'integer'],
            [['listName', 'fullName', 'instagram', 'phone'], 'string', 'max' => 255],
            [['idUser'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\User::className(), 'targetAttribute' => ['idUser' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'idListName' => Yii::t('app', 'Id List Name'),
            'idUser' => Yii::t('app', 'Id User'),
            'listName' => Yii::t('app', 'List Name'),
            'fullName' => Yii::t('app', 'Full Name'),
            'instagram' => Yii::t('app', 'Instagram'),
            'phone' => Yii::t('app', 'Phone'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdUser0()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'idUser']);
    }




}
