<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "vip".
 *
 * @property integer $idVip
 * @property string $name
 * @property integer $amount
 * @property integer $priceForSurplus
 *
 * @property \common\models\Table[] $tables
 * @property \common\models\VipManager[] $vipManagers
 * @property string $aliasModel
 */
abstract class Vip extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'vip';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'amount'], 'required'],
            [['amount', 'priceForSurplus'], 'integer'],
            [['name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'idVip' => 'Id Vip',
            'name' => 'Name',
            'amount' => 'Amount',
            'priceForSurplus' => 'Price For Surplus',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTables()
    {
        return $this->hasMany(\common\models\Table::className(), ['idVip' => 'idVip']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVipManagers()
    {
        return $this->hasMany(\common\models\VipManager::className(), ['idVip' => 'idVip']);
    }




}
