<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "vip_manager".
 *
 * @property integer $idVipManager
 * @property integer $idVip
 * @property integer $idUser
 *
 * @property \common\models\Vip $idVip0
 * @property \common\models\User $idUser0
 * @property string $aliasModel
 */
abstract class VipManager extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'vip_manager';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['idVip', 'idUser'], 'required'],
            [['idVip', 'idUser'], 'integer'],
            [['idVip'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Vip::className(), 'targetAttribute' => ['idVip' => 'idVip']],
            [['idUser'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\User::className(), 'targetAttribute' => ['idUser' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'idVipManager' => 'Id Vip Manager',
            'idVip' => 'Id Vip',
            'idUser' => 'Id User',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdVip0()
    {
        return $this->hasOne(\common\models\Vip::className(), ['idVip' => 'idVip']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdUser0()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'idUser']);
    }




}
